
services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ./
    container_name: app
    restart: always
    depends_on:
      - db
    env_file:
    - .env
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
